services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  cajax.session:
    class: LeadingSystems\CajaxBundle\Services\Session
    public: true

  cajax.eventlistener.kernellistener:
    class: LeadingSystems\CajaxBundle\EventListener\KernelListener
    tags:
      - { name: kernel.event_listener, event: kernel.controller_arguments }